---
dist: bionic
sudo: required

language: python
python:
  - "3.8"

services:
  - docker

before_install:
  - git clone https://github.com/lean-delivery/ansible-lint-rules.git ~/ansible-lint-rules

install:
  - pip3 install --upgrade docker
  - pip3 install ansible-core==2.11.1 ansible-lint==5.0.12 ansible==4.0.0
  - pip3 install molecule==3.3.4
  - pip3 install git+https://github.com/ansible/ansible-lint.git
  - ansible --version
  - ansible-lint --version

script:
  - yamllint . -c .yamllint
  - ansible-lint . -c .ansible-lint
  - molecule test -s test-docker

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
