---
dist: bionic
sudo: required

language: python
python:
  - "3.8"

services:
  - docker

env:
  global:
    - DOCKER_COMPOSE_VERSION="1.29.2"
    - DOCKER_REGISTRY_URL="https://github.com/docker/compose/releases/download"
before_install:
  - sudo curl -L "${DOCKER_REGISTRY_URL}/${DOCKER_COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose
  - ls -l /usr/local/bin/docker-compose
install:
  - docker-compose up --build --detach
script:
  - docker ps
  - docker exec toolset yamllint . -c .yamllint
  - docker exec toolset ansible-lint . -c .ansible-lint
  - docker exec toolset molecule test -s test-docker
  - docker rm -f toolset

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
