---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
  ansible-lint
platforms:
  - name: test-docker-centos7-myrole1
    image: leandelivery/docker-systemd:centos7
    privileged: true
    groups:
      - rhel_family
  - name: test-docker-ubuntu1804-myrole1
    image: leandelivery/docker-systemd:ubuntu-18.04
    privileged: true
    security_opts:
      - seccomp=unconfined
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /tmp
      - /run
    capabilities:
      - SYS_ADMIN
    groups:
      - debian_family
provisioner:
  name: ansible
  log: true
  playbooks:
    verify: ../resources/tests/verify.yml
scenario:
  name: default
verifier:
  name: ansible
