---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: delegated
lint: |
  set -e
  yamllint .
  ansible-lint
  ansible-lint
platforms:
  - name: test-epc-centos7-myrole1
    image: CentOS7_64-bit
    shape: small
    region: EPAM-BY2
    wait_timeout: 3600
    groups:
      - rhel_family
  - name: test-epc-ubuntu1804-myrole1
    image: Ubuntu18.04_64-bit
    shape: small
    region: EPAM-BY2
    wait_timeout: 3600
    groups:
      - debian_family
provisioner:
  name: ansible
  log: true
  playbooks:
    create: ../resources/provisioning/EPC/create.yml
    prepare: ../resources/provisioning/EPC/prepare.yml
    destroy: ../resources/provisioning/EPC/destroy.yml
    verify: ../resources/tests/verify.yml
  config_options:
    ssh_connection:
      control_path: "/var/ans/%%h"
scenario:
  name: cloud-epc-delegated
verifier:
  name: ansible
  options:
    verbose: true
  directory: ../resources/tests/
